# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui-TEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1264, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1241, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn_Simulate = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Simulate.setGeometry(QtCore.QRect(670, 790, 111, 31))
        self.Btn_Simulate.setObjectName("Btn_Simulate")
        self.Btn_Export = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Export.setGeometry(QtCore.QRect(480, 790, 111, 31))
        self.Btn_Export.setObjectName("Btn_Export")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 10, 71, 31))
        self.label.setObjectName("label")
        self.cBox_Customer = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_Customer.setGeometry(QtCore.QRect(710, 10, 151, 31))
        self.cBox_Customer.setObjectName("cBox_Customer")
        self.Btn_Input = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Input.setGeometry(QtCore.QRect(370, 10, 91, 31))
        self.Btn_Input.setObjectName("Btn_Input")
        self.label_noti = QtWidgets.QLabel(self.centralwidget)
        self.label_noti.setGeometry(QtCore.QRect(350, 40, 131, 21))
        self.label_noti.setObjectName("label_noti")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Simulate.setText(_translate("MainWindow", "Simulate"))
        self.Btn_Export.setText(_translate("MainWindow", "Export"))
        self.label.setText(_translate("MainWindow", "Customer:"))
        self.Btn_Input.setText(_translate("MainWindow", "Input file"))
        self.label_noti.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\"><br/></span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
